name: Update Plugin Changelog

on:
  pull_request:
    types:
      - closed

jobs:
  update-changelog:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y subversion
          gem install github_changelog_generator

      - name: Generate Changelog
        run: |
          github_changelog_generator --user ${{ github.repository_owner }} --project ${{ github.event.repository.name }} --token ${{ secrets.GITHUB_TOKEN }}
          # Format the changelog for WordPress
          awk '
          BEGIN { print "== Changelog ==" }
          {
            gsub("## \\[(.*)\\] - (.*)", "= \\1 - \\2 =");
            gsub("- ", "");
            print;
          }
          ' CHANGELOG.md > formatted_changelog.txt

      - name: Update readme.txt
        run: |
          # Remove old changelog entries in readme.txt before appending new ones
          sed -i '/== Changelog ==/,$d' readme.txt
          cat formatted_changelog.txt >> readme.txt

      - name: Commit and Push Changes to GitHub
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add readme.txt
          git commit -m "Update changelog for version ${{ github.event.pull_request.head.ref }}"
          git push origin development
