name: Run checks
on:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4.1.0
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Install Dependencies
        run: npm install --legacy-peer-deps
		
      - name: Run JS Lint
        if: success() || failure()
        run: npm run lint:js

      - name: Run CSS Lint
        if: success() || failure()
        run: npm run lint:css

      - name: Run package.json Lint
        if: success() || failure()
        run: npm run lint:pkg-json
